version: "3.8"

services:
  myjenkins:
    container_name: my_custom_jenkins
    image: jenkins/jenkins:lts
    user: root
    environment:
      MY_NAME: "santi_devops"
      # Gmail extra configuration for mailer plugin
      JAVA_OPTS: "-Djava.awt.headless=true -Dmail.smtp.starttls.enable=true"
      SONARQUBE_HOST: mysonarqube
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      # WARNING: Be cautious with this as it can be a security risk
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net_devops
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G

  mysonarqube:
    container_name: my_custom_sonarqube
    image: sonarqube:latest  # Use the latest version or a specific stable version
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    ports:
      - "9000:9000"
    networks:
      - net_devops
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 3G

volumes:
  jenkins_home:
    name: "custom_jenkins_home"
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:

networks:
  net_devops:
    driver: bridge
    name: net_devops